export const HOOK_LAYOUTS = [
  // --- BỐ CỤC VIDEO CHUYỂN ĐỔI CAO ---
  "Câu chuyện chủ đề + giới thiệu sản phẩm + đánh giá so sánh + sử dụng sản phẩm trong nhiều trường hợp + CTA",
  "Hình thức phỏng vấn + chia sẻ trải nghiệm người dùng + giới thiệu sản phẩm + CTA",
  "Chủ đề đời sống + đánh giá so sánh + điểm nổi bật + sử dụng sản phẩm trong nhiều trường hợp",
  "Nỗi đau + nguyên nhân + bán hàng từ NSX + uy tín thương hiệu + CTA",
  "Hình ảnh cá nhân (người nổi tiếng) + nỗi đau + trải nghiệm thực tế + đánh giá so sánh + bằng chứng + giá trị cộng thêm + CTA",
  "Chia sẻ chân thực + kiến thức ngành + giới thiệu chức năng + đặc điểm nổi bật + ưu đãi + CTA",
  "Thu hút đối tượng mục tiêu cụ thể + câu hỏi từ góc độ người dùng + giải đáp + giới thiệu sản phẩm + ưu đãi + CTA",
  "Nỗi đau trong cuộc sống + nhạc nền kết hợp sử dụng sản phẩm + so sánh độc lập",
  "Kết quả và đánh giá trước + nỗi đau + giới thiệu sản phẩm + ưu đãi + CTA",
  "Hình ảnh cá nhân + nỗi đau trong cuộc sống + trải nghiệm thực tế + giới thiệu sản phẩm/chức năng + trường hợp sử dụng + CTA",
  "Câu hỏi + giải pháp cho nỗi đau + đặc điểm nổi bật sản phẩm + đảm bảo từ nhiều góc độ/trường hợp + CTA",
  "Nỗi đau theo khu vực + giới thiệu sản phẩm + hoàn cảnh sử dụng + cảm nhận khi trải nghiệm + đảm bảo + CTA",
  "Sở thích + giới thiệu sản phẩm + so sánh + giải thích về giá trị + đảm bảo + CTA",
  "Xác định đối tượng mục tiêu + giới thiệu sản phẩm + hướng dẫn sử dụng + thử nghiệm + đánh giá + CTA",
  "Phụ đề ưu đãi + giới thiệu chức năng sản phẩm + trường hợp sử dụng thực tế + ưu đãi",
  "Phản hồi và trải nghiệm của người dùng + kiến thức chuyên môn + nỗi đau + giới thiệu sản phẩm + ưu đãi + CTA",
  "Tình huống tréo ngoe + giải pháp xuất hiện + hướng dẫn sử dụng + kết quả rạng rỡ + CTA",
  "Bóc phốt/Sự thật ngầm hiểu + đính chính bằng sản phẩm + test trực tiếp + phản hồi khách hàng + CTA",
  "Kể chuyện quá khứ (khi chưa có sản phẩm) + bước ngoặt thay đổi + tính năng chủ chốt + CTA",
  "Thách thức 7 ngày sử dụng + nhật ký thay đổi mỗi ngày + kết quả cuối cùng + lời khuyên + CTA",
  "So sánh hàng giá rẻ vs. Sản phẩm chính hãng + phân tích cấu tạo/thành phần + bài học chi phí + CTA",
  "Tin tức xu hướng (Trending) + cách sản phẩm giải quyết vấn đề thời sự + lợi ích thực tế + CTA",
  "Hậu trường sản xuất/Quy trình tạo ra sản phẩm + cam kết chất lượng + trải nghiệm thực tế + CTA",
  "Phân tích thành phần chuyên sâu + so sánh với tiêu chuẩn ngành + chứng chỉ uy tín + CTA",
  "Review từ người khó tính nhất + hành trình bị thuyết phục + điểm 10 chất lượng + CTA",
  "Kịch bản 'Tiết kiệm' + phân tích bài toán kinh tế khi dùng sản phẩm + độ bền/tái sử dụng + CTA",
  "Cảnh báo rủi ro nếu không dùng sản phẩm + kịch bản giả định + giải pháp ngăn ngừa + CTA",
  "Tổng hợp feedback tích cực + chứng thực từ cộng đồng + lời cảm ơn khách hàng + ưu đãi tri ân + CTA",

  // --- CÂU HOOK ĐA NĂNG (DÙNG CHO MỌI NGÀNH HÀNG) ---
  "-----------------------------------------------------------------------",
  "Phải công nhận thật 1 điều là cái [sản phẩm] nó quá là [đặc điểm] luôn.",
  "Không cần tốn quá nhiều chi phí cho [vấn đề] nữa bởi vì chỉ cần 1 [sản phẩm] này thôi.",
  "Khi dùng món đồ này thì [lợi ích] ở khắp mọi nơi luôn anh em ạ.",
  "Nếu anh em là tín đồ [sở thích] thì cái [sản phẩm] này đúng là không thể thiếu.",
  "Mình vẫn đang thắc mắc là vẫn có những anh em đang sử dụng [cách cũ] để [mục tiêu].",
  "Mình dám cá là anh em sẽ bất ngờ với con [sản phẩm], bởi vì nhìn nó [vẻ ngoài] mà [tính năng].",
  "Khi dùng cái [sản phẩm] này thì mấy cái [đồ cũ] anh em cũng vứt hết đi cho mà xem.",
  "Đây là lý do mà anh em chắc chắn không nên bỏ qua chiếc [sản phẩm] này.",
  "Một chiếc [sản phẩm] mà mình rất thích bởi vì đơn giản là khi dùng nó mình không thấy [cảm giác khó chịu].",
  "Anh em đã sai lầm khi nghĩ rằng [quan điểm sai] và đây là [sự thật/sản phẩm].",
  "Cái [sản phẩm] nó quá là tiện anh em ạ, anh em có thể [công dụng 1] hay [công dụng 2].",
  "Việc [nhiệm vụ] bây giờ trở nên quá là đơn giản và đây là [sản phẩm].",
  "Đau đầu vì [vấn đề] quá là [mệt mỏi] trong khi dùng [sản phẩm] thì [kết quả].",
  "Một con [sản phẩm] không bao giờ hết hot, và đây là lý do.",
  "Sau khi đã dùng qua rất nhiều loại thì cuối cùng mình vẫn quyết định quay lại với em [sản phẩm] này.",
  "Top những mẫu [dòng sản phẩm] không thể thiếu ở trong nhà các anh em ngay lúc này.",
  "Mình vẫn chưa bao giờ đánh giá một con [sản phẩm] nào mà cao như con này trong tầm giá.",
  "Anh em có công nhận với mình là cái [sản phẩm] nó quá là [đặc điểm] đúng không?",
  "Hay phải [hành động] thì chắc chắn anh em không nên bỏ qua món đồ này.",
  "Mình đã thực sự hối hận khi không biết đến cái [sản phẩm] này sớm anh em ạ.",
  "Mình đã tìm ra món đồ sẽ giúp anh em cực kỳ [lợi ích] với cái [vấn đề] này.",
  "Gia đình bác nào mà [tình trạng] thì nên sử dụng cái [sản phẩm] để [mục tiêu].",
  "Thay vì sử dụng [cách cũ] thì chúng ta sử dụng [sản phẩm] đây các bạn, cực kỳ là [đặc điểm].",
  "Nếu bạn đang chán với cái [sản phẩm] thông thường thì nhớ tìm mua cái này nha.",
  "Bạn đang cần [nhu cầu] thì làm thế nào? Giới thiệu với các bạn đây là [sản phẩm] chuyên dụng.",
  "Một cái [sản phẩm] mà mình cảm thấy ưng ý nhất, ổn áp trong tầm giá.",
  "Lý do các [đối tượng] không thể [thành công] là do cái này, đây là [sản phẩm].",
  "Mua 1 cái [sản phẩm] mà có n tác dụng, quá tiện lợi rồi còn gì nữa.",
  "Một chiếc [sản phẩm] đa năng mình chắc chắn anh em nào cũng nên có.",
  "Chào mọi người, mình đã quay lại review cho mọi người đây, không thể bỏ qua món này.",
  "Cuối cùng cũng săn được [sản phẩm] với giá hời rồi.",
  "Sau khi dùng hết [số lượng] [đơn vị], mình đã quay lại review cho mọi người đây.",
  "Gần đây mọi người săn lùng [sản phẩm] này dữ quá, có đáng để chị em liên tục tag bạn bè vào không?",
  "Mình đã đợi rất lâu và cuối cùng [sản phẩm] đã giảm giá rồi mọi người ơi.",
  "Nhà anh chị có ai bị [vấn đề] thì gửi ngay clip này cho họ nhé.",
  "Mọi người có biết [vấn đề] là nguyên nhân chính gây ra [hậu quả nghiêm trọng] không?",
  "3 mẹo sau đây giúp [kết quả] ngay khi xem hết video này.",
  "Sau một thời gian, mấy đứa bạn bảo mình [vấn đề] đã phải xin lỗi mình vì [kết quả].",
  "Cái gì làm cho [đối tượng] từ thế này thành thế này? (Show hình ảnh so sánh)",
  "Đừng để [vấn đề] quanh năm nữa, đừng để [hậu quả] rồi mới tìm cách chữa.",
  "3 cách để [mục tiêu] dành cho [đối tượng cụ thể].",
  "Ai hay [vấn đề] bị [phiền toái] thì nên có [sản phẩm] này.",
  "Có bạn nào đang khổ sở vì [vấn đề] không? Thử ngay [giải pháp] này đi!",
  "Ai hay bị [vấn đề] thì coi gấp video này nhé!",
  "Món đồ này đã giúp mình tiết kiệm được [thời gian/công sức] mỗi ngày.",
  "Làm thế nào để [đạt mục tiêu] mà không cần đến [cách làm cũ]?",
  "Cách nhanh nhất để [xử lý vấn đề] bằng [sản phẩm] chuyên dụng.",
  "Cuối cùng thì mình cũng tìm được cách để xử lý [nỗi lo lâu nay].",
  "Ai nghĩ [quan điểm cũ] thì có lẽ là chưa biết tới [giải pháp mới] rồi.",
  "Ước gì mình biết [điều này/món này] sớm hơn thì đã không phải [hậu quả].",
  "Đáng lý [sản phẩm] này phải được chú ý từ lâu vì độ tiện dụng của nó.",
  "Sự thật thú vị có thể bạn chưa biết về việc [chủ đề].",
  "Điều mà [đối tượng chuyên gia] không muốn bạn biết.",
  "Thay vì mua [nhiều thứ rẻ], mình chọn [một thứ đa năng] này.",
  "Món đồ này đã hỗ trợ mình rất nhiều lần khi gặp tình huống [khó khăn].",
  "Mình từng không tin vào quảng cáo cho tới khi tự trải nghiệm [sản phẩm] này.",
  "Một trong những món đồ đáng giá mình từng mua vì [lợi ích cụ thể].",
  "Hiếm khi mình đánh giá thứ gì tới lần thứ hai, trừ [tên sản phẩm] này.",
  "Mình đã thử qua nhiều dòng [sản phẩm], nhưng đây là món mình giữ lại.",
  "Mình đã cải thiện [vấn đề] chỉ nhờ [giải pháp đơn giản].",
  "Cách để đạt được [phong cách/kết quả] như [người nổi tiếng].",
  "Bí mật để [đạt kết quả tốt] mà không cần tốn quá nhiều công sức.",
  "Cẩn thận mất tiền oan khi mua [sản phẩm], dễ gặp tình trạng [vấn đề].",
  "Dừng ngay việc [hành động sai] nếu không muốn [hậu quả xấu].",
  "Trước khi đầu tư vào [sản phẩm], bạn cần lưu ý điều này.",
  "Bạn vẫn chưa biết đến [giải pháp/xu hướng] này sao?",
  "Có ai gặp tình trạng [vấn đề khó chịu] giống như mình không?",
  "Sẽ thế nào nếu bạn áp dụng [giải pháp] này vào [tình huống]?",
  "Tại sao bạn càng [cố gắng làm X] thì kết quả lại càng [tệ]?",
  "Đố bạn biết đâu là nguyên nhân khiến [vấn đề] trở nên nghiêm trọng?",
  "Kiểm chứng lời đồn về loại [sản phẩm] đang quảng cáo là [công dụng].",
  "Những lưu ý không thể bỏ qua khi bạn chọn mua [dòng sản phẩm].",
];
